---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &BankAlphaOrg
        Name: BankAlphaOrg
        ID: BankAlphaMSP
        MSPDir: crypto-config/peerOrganizations/bankalpha.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BankAlphaMSP.admin', 'BankAlphaMSP.peer', 'BankAlphaMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BankAlphaMSP.admin', 'BankAlphaMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BankAlphaMSP.admin')"

    - &BankBetaOrg
        Name: BankBetaOrg
        ID: BankBetaMSP
        MSPDir: crypto-config/peerOrganizations/bankbeta.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BankBetaMSP.admin', 'BankBetaMSP.peer', 'BankBetaMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BankBetaMSP.admin', 'BankBetaMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BankBetaMSP.admin')"
Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *BankAlphaOrg
                    - *BankBetaOrg
    TwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *BankAlphaOrg
                - *BankBetaOrg
            Capabilities:
                <<: *ApplicationCapabilities
