OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: bankalpha
    Domain: bankalpha.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: bankbeta
    Domain: bankbeta.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
